version: "3.8"
services:
  postgreSQL:
    container_name: postgreSQL
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database-data: